In [ ]:
# ЛАБОРАТОРНА РОБОТА 1. NumPy

import numpy as np

# --- 0. Підготовка середовища ---
print("--- Завдання 0 ---")
print("Версія NumPy:", np.__version__)


# --- 1. Створення масивів NumPy ---
print("\n--- Завдання 1 ---")
arr = np.array([2, 4, 6, 8, 10])
print("Масив:", arr)
print("Тип:", type(arr))

print("\n--- Завдання 2 ---")
zeros_arr = np.zeros(10)
ones_arr = np.ones(8)
sevens_arr = np.full(6, 7)
print("1. Нулі:", zeros_arr)
print("2. Одиниці:", ones_arr)
print("3. Сімки:", sevens_arr)

print("\n--- Завдання 3 ---")
arr_full = np.arange(1, 21)
arr_even = np.arange(2, 21, 2)
print("Від 1 до 20:", arr_full)
print("Парні від 2 до 20:", arr_even)

print("\n--- Завдання 4 ---")
lin_arr = np.linspace(0, 1, 11)
print(lin_arr)

print("\n--- Завдання 5 ---")
flat_arr = np.arange(1, 13)
matrix = flat_arr.reshape(3, 4)
print(matrix)


# --- 2. Основні характеристики масивів ---
print("\n--- Завдання 6 ---")
print("Кількість вимірів (ndim):", matrix.ndim)
print("Форма (shape):", matrix.shape)
print("Загальна кількість елементів (size):", matrix.size)
print("Тип даних (dtype):", matrix.dtype)

print("\n--- Завдання 7 ---")
f_arr = np.array([1.2, 3.5, 5.7, 7.9])
int_arr = f_arr.astype(int)
print(int_arr)


# --- 3. Індексація та зрізи ---
print("\n--- Завдання 8 ---")
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("1. Перший елемент:", arr[0])
print("2. Останній елемент:", arr[-1])
print("3. Елементи від 2 до 5 включно:", arr[2:6])
print("4. Кожен другий елемент:", arr[::2])

print("\n--- Завдання 9 ---")
matrix = np.array([[1,  2,  3,  4],
                   [5,  6,  7,  8],
                   [9, 10, 11, 12]])
print("1. Елемент 7:", matrix[1, 2])
print("2. Другий рядок:", matrix[1, :])
print("3. Третій стовпець:", matrix[:, 2])
print("4. Підматриця:\n", matrix[1:, :2])

print("\n--- Завдання 10 ---")
arr = np.arange(1, 16)
arr[5:10] = 0
print(arr)


# --- 4. Арифметичні операції та агрегатні функції ---
print("\n--- Завдання 11 ---")
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print("Додавання:", a + b)
print("Віднімання:", a - b)
print("Множення:", a * b)
print("Ділення:", a / b)

print("\n--- Завдання 12 ---")
arr = np.array([4, 8, 15, 16, 23, 42])
print("Сума:", np.sum(arr))
print("Середнє значення:", np.mean(arr))
print("Мінімум:", np.min(arr))
print("Максимум:", np.max(arr))
print("Медіана:", np.median(arr))
print("Стандартне відхилення:", np.std(arr))

print("\n--- Завдання 13 ---")
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("1. Сума всіх елементів:", np.sum(matrix))
print("2. Сума по кожному стовпцю:", np.sum(matrix, axis=0))
print("3. Сума по кожному рядку:", np.sum(matrix, axis=1))
print("4. Середнє значення по кожному стовпцю:", np.mean(matrix, axis=0))

print("\n--- Завдання 14 ---")
arr = np.arange(1, 11)
print("Квадрат кожного елемента:", np.square(arr))
print("Квадратний корінь:", np.sqrt(arr))
print("Натуральний логарифм:", np.log(arr))


# --- 5. Логічні операції та фільтрація ---
print("\n--- Завдання 15 ---")
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])
print("1. Більші за 15:", arr[arr > 15])
print("2. Парні числа:", arr[arr % 2 == 0])
print("3. У діапазоні від 10 до 30 включно:", arr[(arr >= 10) & (arr <= 30)])

print("\n--- Завдання 16 ---")
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
arr[arr < 0] = 0
print(arr)

print("\n--- Завдання 17 ---")
np.random.seed(42)
arr = np.random.randint(0, 101, size=20)
print("Масив:", arr)
print("Більші за 50:", np.sum(arr > 50))
print("Менші або дорівнюють 50:", np.sum(arr <= 50))


# --- 6. Зміна форми та об'єднання масивів ---
print("\n--- Завдання 18 ---")
arr = np.arange(1, 25)
m1 = arr.reshape(4, 6)
print("1. Shape (4x6):", m1.shape)
m2 = arr.reshape(6, 4)
print("2. Shape (6x4):", m2.shape)
m3 = arr.reshape(2, 3, 4)
print("3. Shape (2x3x4):", m3.shape)

print("\n--- Завдання 19 ---")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("1. Вертикальне об'єднання:\n", np.vstack((A, B)))
print("2. Горизонтальне об'єднання:\n", np.hstack((A, B)))

print("\n--- Завдання 20 ---")
matrix = np.arange(1, 13).reshape(3, 4)
f1 = matrix.flatten()
f2 = matrix.ravel()
print("flatten():", f1)
print("ravel():", f2)
print("Ідентичні за значеннями:", np.array_equal(f1, f2))


# --- 7. Дії з векторами ---
print("\n--- Завдання 21 ---")
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
print("Сума векторів:", a + b)
print("Різниця векторів:", a - b)
print("Множення вектора a на 3:", a * 3)
print("Множення вектора b на 3:", b * 3)

print("\n--- Завдання 22 ---")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("1. np.dot():", np.dot(a, b))
print("2. Оператор @:", a @ b)

print("\n--- Завдання 23 ---")
v = np.array([3, 4])
norm = np.linalg.norm(v)
print("Евклідова норма:", norm)
print("Нормалізований вектор:", v / norm)

print("\n--- Завдання 24 ---")
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
print("Векторний добуток:", np.cross(a, b))

print("\n--- Завдання 25 ---")
a = np.array([1, 2])
b = np.array([2, 1])
cos_angle = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
angle_deg = np.degrees(np.arccos(cos_angle))
print("Косинус кута:", cos_angle)
print("Кут у градусах:", angle_deg)


# --- 8. Дії з матрицями ---
print("\n--- Завдання 26 ---")
A = np.array([[1, 2, 3], [4, 5, 6]])
print("1. Через .T:\n", A.T)
print("2. Через np.transpose():\n", np.transpose(A))

print("\n--- Завдання 27 ---")
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
print("1. Поелементний добуток (A * B):\n", A * B)
print("2. Матричний добуток (A @ B):\n", A @ B)

print("\n--- Завдання 28 ---")
A = np.array([[4, 7], [2, 6]])
det = np.linalg.det(A)
inv = np.linalg.inv(A)
print("Визначник:", det)
print("Обернена матриця:\n", inv)
print("Перевірка (A @ inv):\n", A @ inv)

print("\n--- Завдання 29 ---")
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print("Розв'язок системи (x, y):", x)

print("\n--- Завдання 30 ---")
I = np.eye(4)
rand_m = np.random.randint(1, 10, size=(4, 4))
res = I @ rand_m
print("Одинична матриця:\n", I)
print("Результат множення на довільну матрицю:\n", res)
print("Збігається з початковою:", np.array_equal(res, rand_m))


# --- 9. Broadcasting (операція трансляції) ---
print("\n--- Завдання 31 ---")
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A + 10)

print("\n--- Завдання 32 ---")
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = np.array([10, 20, 30])
print(A + v)

print("\n--- Завдання 33 ---")
A = np.array([[10, 20, 30], [20, 30, 40], [30, 40, 50]], dtype=float)
mu = np.mean(A, axis=0)
sigma = np.std(A, axis=0)
normalized = (A - mu) / sigma
print(normalized)


# --- 10. Випадкові дані ---
print("\n--- Завдання 34 ---")
np.random.seed(42)
print("1. Випадкові цілі:", np.random.randint(1, 101, size=10))
print("2. Матриця 3x3:\n", np.random.rand(3, 3))
normal_dist = np.random.randn(1000)
print("3. Нормальний розподіл -> Середнє:", np.mean(normal_dist), ", СКВ:", np.std(normal_dist))

print("\n--- Завдання 35 ---")
np.random.seed(42)
scores = np.random.randint(0, 101, size=30)
print("Оцінки:", scores)
print("Середня оцінка:", np.mean(scores))
print("Медіана:", np.median(scores))
print("Найвища:", np.max(scores), "| Найнижча:", np.min(scores))
print("Кількість >= 60:", np.sum(scores >= 60))
print("Відсоток >= 90:", np.mean(scores >= 90) * 100, "%")


# --- 11. Підсумкові завдання ---
print("\n--- Завдання 36 ---")
sales = np.array([[120, 150, 170, 160],
                  [80,  90,  100, 110],
                  [200, 180, 210, 230]])
print("1. Загальний обсяг продажів кожного товару:", np.sum(sales, axis=1))
print("2. Загальний обсяг продажів у кожному місяці:", np.sum(sales, axis=0))
print("3. Товар із найбільшими сумарними продажами (індекс):", np.argmax(np.sum(sales, axis=1)))
print("4. Місяць із найбільшим загальним обсягом продажів (індекс):", np.argmax(np.sum(sales, axis=0)))
print("5. Середній обсяг продажів кожного товару:", np.mean(sales, axis=1))

print("\n--- Завдання 37 ---")
np.random.seed(42)
mat = np.random.randint(1, 21, size=(5, 5))
print("Матриця:\n", mat)
print("1. Сума головної діагоналі:", np.sum(np.diag(mat)))
print("2. Сума побічної діагоналі:", np.sum(np.diag(np.fliplr(mat))))
print("3. Максимальний елемент кожного рядка:", np.max(mat, axis=1))
print("4. Мінімальний елемент кожного стовпця:", np.min(mat, axis=0))
mean_val = np.mean(mat)
mat_mod = mat.copy()
mat_mod[mat_mod < mean_val] = 0
print(f"5. Матриця після заміни елементів < середнього ({mean_val:.2f}) на 0:\n", mat_mod)

print("\n--- Завдання 38 ---")
X = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])
d12 = np.linalg.norm(X[0] - X[1])
d13 = np.linalg.norm(X[0] - X[2])
d23 = np.linalg.norm(X[1] - X[2])
print("Відстань між 1 і 2 рядком:", d12)
print("Відстань між 1 і 3 рядком:", d13)
print("Відстань між 2 і 3 рядком:", d23)

print("\n--- Завдання 39 ---")
np.random.seed(42)
M = np.random.randint(-10, 10, size=(4, 4)).astype(float)
norms = np.linalg.norm(M, axis=1, keepdims=True)
normalized_M = M / norms
print("Нормалізована матриця:\n", normalized_M)

print("\n--- Завдання 40 ---")
A = np.array([[1,  2,  1],
              [2,  1, -1],
              [3, -1,  2]])
b = np.array([9, 8, 3])
x = np.linalg.solve(A, b)
print("1. Розв'язок системи x:", x)
res_mult = A @ x
print("2. Матричний добуток A @ x:", res_mult)
print("3. Збігається з вектором b:", np.allclose(res_mult, b))

--- Завдання 0 ---
Версія NumPy: 2.1.3

--- Завдання 1 ---
Масив: [ 2  4  6  8 10]
Тип: <class 'numpy.ndarray'>

--- Завдання 2 ---
1. Нулі: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2. Одиниці: [1. 1. 1. 1. 1. 1. 1. 1.]
3. Сімки: [7 7 7 7 7 7]

--- Завдання 3 ---
Від 1 до 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Парні від 2 до 20: [ 2  4  6  8 10 12 14 16 18 20]

--- Завдання 4 ---
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

--- Завдання 5 ---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

--- Завдання 6 ---
Кількість вимірів (ndim): 2
Форма (shape): (3, 4)
Загальна кількість елементів (size): 12
Тип даних (dtype): int64

--- Завдання 7 ---
[1 3 5 7]

--- Завдання 8 ---
1. Перший елемент: 10
2. Останній елемент: 80
3. Елементи від 2 до 5 включно: [30 40 50 60]
4. Кожен другий елемент: [10 30 50 70]

--- Завдання 9 ---
1. Елемент 7: 7
2. Другий рядок: [5 6 7 8]
3. Третій стовпець: [ 3  7 11]
4. Підматриця:
 [[ 5  6]
 [ 9 10]]

--- Завдання 10 ---
[ 1  2  3  4  5  0  0